FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml poetry.lock* requirements*.txt* /app/
# choose either poetry or pip:
RUN pip install --no-cache-dir fastapi uvicorn[standard] pandas numpy sqlalchemy pymysql prometheus_client
COPY src /app/src
ENV PYTHONPATH=/app/src
EXPOSE 8000
CMD ["uvicorn","api.main:app","--host","0.0.0.0","--port","8000"]