# docker-compose.yml

version: '3.8'

services:
  # --------------------------------------------------------------------------
  # Hadoop NameNode Service
  # --------------------------------------------------------------------------
  namenode:
    image: big-data-europe/hadoop-namenode:3.3.6 # Apache Hadoop NameNode image
    hostname: namenode
    container_name: namenode
    ports:
      - "9870:9870" # Hadoop NameNode Web UI (Hadoop 3.x default)
      - "9000:9000" # HDFS default port for client communication
    volumes:
      - namenode-data:/hadoop/dfs/name # Persistent storage for NameNode metadata
    environment:
      - CLUSTER_NAME=test-cluster
      - HDFS_USER=hdfs
    env_file:
      - ./hadoop.env # Additional Hadoop environment variables (HADOOP_PORT, HDFS_REPLICATION)
    networks:
      - big-data-net # Connect to custom network
    healthcheck:
      test: ["CMD", "hdfs", "dfsadmin", "-report"] # Check NameNode health
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 1g # Allocate 1GB RAM to NameNode (adjust as needed)

  # --------------------------------------------------------------------------
  # Hadoop DataNode Service
  # --------------------------------------------------------------------------
  datanode:
    image: big-data-europe/hadoop-datanode:3.3.6 # Apache Hadoop DataNode image
    hostname: datanode
    container_name: datanode
    volumes:
      - datanode-data:/hadoop/dfs/data # Persistent storage for DataNode blocks
    environment:
      - CLUSTER_NAME=test-cluster
      - HDFS_USER=hdfs
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000 # Link to NameNode
    env_file:
      - ./hadoop.env
    networks:
      - big-data-net
    depends_on:
      namenode:
        condition: service_healthy # Ensure NameNode is healthy before DataNode starts
    mem_limit: 2g # Allocate 2GB RAM to DataNode (adjust as needed)

  # --------------------------------------------------------------------------
  # MariaDB Service (for Hive Metastore)
  # --------------------------------------------------------------------------
  mariadb:
    image: mariadb:10.6 # Stable MariaDB image
    hostname: mariadb
    container_name: mariadb
    ports:
      - "3306:3306" # Expose MariaDB port for potential external tools (optional)
    volumes:
      - mariadb-data:/var/lib/mysql # Persistent storage for MariaDB data
    environment:
      - MARIADB_ROOT_PASSWORD=your_root_password # !!! CHANGE THIS PASSWORD !!!
      - MARIADB_DATABASE=hive_metastore # Database for Hive
      - MARIADB_USER=hive # Hive user
      - MARIADB_PASSWORD=hive_password # !!! CHANGE THIS PASSWORD !!! Hive user password
    networks:
      - big-data-net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p$$MARIADB_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m # Allocate 512MB RAM (adjust as needed)

  # --------------------------------------------------------------------------
  # Hive Service (Metastore and HiveServer2)
  # --------------------------------------------------------------------------
  hive-server:
    image: big-data-europe/hive:3.1.3 # Apache Hive image
    hostname: hive-server
    container_name: hive-server
    ports:
      - "10000:10000" # HiveServer2 Thrift UI
      - "9083:9083" # Hive Metastore service
    environment:
      - SERVICE_PRECONDITION=namenode:9000 # Wait for NameNode to be ready
      - HIVE_DATABASE_TYPE=mysql # Use MySQL (MariaDB) as Metastore
      - HIVE_DB_USERNAME=hive
      - HIVE_DB_PASSWORD=hive_password # Must match MariaDB password
      - HIVE_DB_URL=jdbc:mysql://mariadb:3306/hive_metastore?createDatabaseIfNotExist=true # JDBC URL for Metastore DB
      - HIVE_CONF_hadoop_bin_path=/opt/hadoop/bin # Path to Hadoop client within container
      - HIVE_CONF_hive_metastore_warehouse_dir=/user/hive/warehouse # HDFS warehouse directory
    networks:
      - big-data-net
    depends_on:
      namenode:
        condition: service_healthy # Ensure NameNode is healthy
      mariadb:
        condition: service_healthy # Ensure MariaDB is healthy
    mem_limit: 1.5g # Allocate 1.5GB RAM (adjust as needed)

  # --------------------------------------------------------------------------
  # MongoDB Service
  # --------------------------------------------------------------------------
  mongodb:
    image: mongo:6.0 # Stable MongoDB image
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB default port
    volumes:
      - mongodb-data:/data/db # Persistent storage for MongoDB data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser # !!! CHANGE THIS USERNAME !!!
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword # !!! CHANGE THIS PASSWORD !!!
    networks:
      - big-data-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')", "--quiet"] # MongoDB health check
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m # Allocate 512MB RAM (adjust as needed)

  # --------------------------------------------------------------------------
  # JupyterLab Service
  # --------------------------------------------------------------------------
  jupyterlab:
    image: jupyter/scipy-notebook:latest # JupyterLab with common scientific libraries
    hostname: jupyterlab
    container_name: jupyterlab
    ports:
      - "8888:8888" # JupyterLab Web UI
    volumes:
      - ./notebooks:/home/jovyan/work # Mount local 'notebooks' directory for persistence
    environment:
      - JUPYTER_ENABLE_LAB=yes # Enable JupyterLab
      - GRANT_SUDO=yes # Allow sudo for 'jovyan' user
      - NB_UID=1000 # User ID for 'jovyan'
      - NB_GID=100 # Group ID for 'jovyan'
      # Environment variables for connecting to other services (useful for examples)
      - HADOOP_NAMENODE_HOST=namenode
      - HIVE_SERVER_HOST=hive-server
      - HIVE_SERVER_PORT=10000
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_USER=hive
      - MARIADB_PASSWORD=hive_password
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=mongouser
      - MONGODB_PASSWORD=mongopassword
    networks:
      - big-data-net
    depends_on:
      namenode:
        condition: service_healthy
      hive-server:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    mem_limit: 1.5g # Allocate 1.5GB RAM (adjust as needed, more for heavy analysis)
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.allow_origin='*' # For easier access; in production, use a strong token or disable external access

# --------------------------------------------------------------------------
# Docker Volumes for Persistent Data
# --------------------------------------------------------------------------
volumes:
  namenode-data: # For Hadoop NameNode metadata
  datanode-data: # For Hadoop DataNode blocks
  mariadb-data:  # For MariaDB database files
  mongodb-data:  # For MongoDB database files

# --------------------------------------------------------------------------
# Docker Network for Inter-Service Communication
# --------------------------------------------------------------------------
networks:
  big-data-net:
    driver: bridge # Standard bridge network for all services