[mypy]
python_version = 3.12
mypy_path = src
explicit_package_bases = True
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_optional = True
check_untyped_defs = True

# third-party types
[mypy-requests.*]
ignore_missing_imports = True

[mypy-yfinance.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-pymysql.*]
ignore_missing_imports = True
[mypy-pymysql.cursors.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-pyhive.*]
ignore_missing_imports = True