apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: big-data
resources:
  - ns.yaml
  - airflow-postgres.yaml
  - airflow-webserver.yaml
  - airflow-scheduler.yaml
  - marquez-db.yaml
  - marquez-api.yaml
  - marquez-web.yaml
configMapGenerator:
  - name: marquez-config
    files:
      - config.yml=marquez-config.yml
  - name: airflow-env
    literals:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__OPENLINEAGE__NAMESPACE=dev
      - AIRFLOW__OPENLINEAGE__TRANSPORT={"type":"http","url":"http://marquez-api:5000"}
  - name: marquez-env
    literals:
      - MARQUEZ_DB_URL=jdbc:postgresql://marquez-db:5432/marquez
      - MARQUEZ_DB_USER=marquez
      - MARQUEZ_DB_PASSWORD=marquez
      - MARQUEZ_PORT=5000
secretGenerator:
  - name: airflow-secrets
    literals:
      - AIRFLOW_UID=50000
      - MARIADB_ROOT_PASSWORD=password
      - AIRFLOW_CONN_HIVE_DEFAULT=hive://hive-server:10000/default?auth=NOSASL
      - AIRFLOW_CONN_MARIADB_DEFAULT=mysql://root:password@mariadb:3306/analytics
  - name: pg-airflow-secrets
    literals:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  - name: pg-marquez-secrets
    literals:
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
      - POSTGRES_DB=marquez